# Generated by Django 5.1.1 on 2024-09-15 18:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_product_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('message', models.CharField(max_length=400)),
                ('date_time', models.DateTimeField(default=datetime.datetime.today, verbose_name='Date')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.CharField(max_length=300),
        ),
    ]
